### ISSUE TITLE
Demo with changable parameters?

### ISSUE THREAD

**Issue by katerlouis** [d4nyll/lethargy#22]
http://jsfiddle.net/q6reLg0v/
The jsfiddle demo is nice, but not of much use when testing custom options. 

If you don't have the time to make a dynamic demo, can you tell a way on how to hijack the fiddle? I don't find the initialization of lethargy in the js-code there.

Thanks!

**Comment by d4nyll** [comment]
@katerlouis Apologies for the late reply.

That demo is not a demo of lethargy. It's just a way for you to see the delta values of your scroll. [This](http://d4nyll.github.io/lethargy/) is the demo for lethargy, which you can [download](https://github.com/d4nyll/lethargy/tree/gh-pages) and update the parameters passed to the [constructor](https://github.com/d4nyll/lethargy/blob/gh-pages/index.html#L46).
