### ISSUE TITLE
2 "compatibility" propositions

### ISSUE THREAD

**Issue by ayamflow** [d4nyll/lethargy#3]
Hi there,
this is a very nice library :+1: been struggling with these issues for a while.

Would you be interested in having this working standalone, without jQuery? Since it's not dependant on any jQuery feature, allowing to use `e` instead of `e.originalEvent` would do the trick.

Would you also be interested in making this npm (browserify) compatible? It just needs a proper package.json so you can publish on npm, since the source already has the `exports` variables.

I think those 2 propositions would make the library more easily accessible to a wide range of user.

Let me know, I can make a PR for each of those later.

**Comment by ayamflow** [comment]
:+1:

**Comment by d4nyll** [comment]
@ayamflow Thank you for your feedback and suggestion, it is very much appreciated! Since it's not too much work, I went ahead and did it already.

Can you help me debug a little? After removing `originalEvent`, it doesn't seem to work anymore, and I don't have time these few days to work on it. I will accept any PR. Thanks.

**Comment by ayamflow** [comment]
Sure!
If you want to keep jQuery compatibility, I think it's better to just test if originalEvent exists, otherwise falling back on event:

``` coffee
 check: (e) ->
    e = e.originalEvent || e
    ...
```

**Comment by d4nyll** [comment]
I need to learn to use Git properly...I tried reverting the commit and now I lost like the last 7...glad I still got it locally.

**Comment by d4nyll** [comment]
Thanks for that @ayamflow Can you please do me a massive favour and check that it still works with and without jQuery?

**Comment by ayamflow** [comment]
I can check tonight & add some tests if you want.

**Comment by d4nyll** [comment]
That'd be great! Adding tests would really be a nice touch! I'm following you on Twitter! Thanks for your help!
