### ISSUE TITLE
Include an index.js file for require module system

### ISSUE THREAD

**Issue by Samsy** [d4nyll/lethargy#6]

**Comment by baptistebriel** [comment]
why? the `main` field in package.json is correct:
https://github.com/d4nyll/lethargy/blob/master/package.json#L5

are you having troubles using it on npm? I know the latest version is not online but you could use the git repo as dependency:

`"lethargy": "git+https://github.com/d4nyll/lethargy.git"`

**Comment by Samsy** [comment]
Yeah, I appeared to be drunk while writing this issue.
Was a long time ago haha
