### ISSUE TITLE
Tolerates false negatives ?

### ISSUE THREAD

**Issue by alvarotrigo** [d4nyll/lethargy#7]
From the docs:

> Lethargy focus on preventing false positives (saying it's a normal scroll event when it wasn't), **but tolerates false negatives (saying it's not a normal scroll event when it is).**

Isn't there a way to know when it is a normal scroll then ? 

Using the [demo page](http://d4nyll.github.io/lethargy/) I can scroll for the first time and get only `false` values. Meaning "this is not a normal scroll" when in fact it is.

**Comment by d4nyll** [comment]
Hey @alvarotrigo thanks for the quick reply from fullPage.js's issue tracker

I am not sure what you mean. When you first scroll, the first 15 events will always be considered valid scrolls. The first 15 events fills up an array which I use to do averages etc later on, and it's a number that's adjustable. Looking at the source code of fullPage.js, I see you've done something similar.

So you shouldn't get `false` values when you scroll for the first time, after a hard refresh.

**Comment by alvarotrigo** [comment]
Right. I was clearing the console. 
You can scroll hard. Clear the console and then get only false if you scroll slowly. Although now that I think about it is not something bad. 

I'll keep playing with it a bit more!

**Comment by d4nyll** [comment]
Yeah, I've been playing around with it for a while, seems a lot like black magic. Be good to have a second pair of eyes on it. Many thanks!
